name: flutter_ddd
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  auto_route: 3.2.2
  bloc: 7.0.0
  dartz: ^0.10.1
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: 7.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.3
  injectable: ^1.5.3
  intl: ^0.17.0
  kt_dart: ^0.10.0
  uuid: ^3.0.5

dependency_overrides:
  analyzer: ^3.0.0

dev_dependencies:
  auto_route_generator: 3.2.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
