// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3wLyLQMH2ZbNIuQxjcWPUOeIOyDyKIsA',
    appId: '1:465061791880:web:91cc163ee438fa1796373d',
    messagingSenderId: '465061791880',
    projectId: 'note-app-13c74',
    authDomain: 'note-app-13c74.firebaseapp.com',
    storageBucket: 'note-app-13c74.appspot.com',
    measurementId: 'G-BK1YT051LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4j6Zwqta3Y0joYwRBm-BibPfc8IYbKf8',
    appId: '1:465061791880:android:a3fe0819d7ad153896373d',
    messagingSenderId: '465061791880',
    projectId: 'note-app-13c74',
    storageBucket: 'note-app-13c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0C2PFkHMLQrfPz7-NGD7btCFdmEVQXf4',
    appId: '1:465061791880:ios:1334b7c1343a6c9196373d',
    messagingSenderId: '465061791880',
    projectId: 'note-app-13c74',
    storageBucket: 'note-app-13c74.appspot.com',
    androidClientId: '465061791880-hs39l4ovor9pdglmkio0ifk7egfmtg3m.apps.googleusercontent.com',
    iosClientId: '465061791880-9rc4df6epkkbrtcipn9h9mpn99gr2q86.apps.googleusercontent.com',
    iosBundleId: 'com.ajaygujja.flutterDDD',
  );
}
